/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es/components/config-provider/index')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es/components/dialog/index')['ElDialog']
    ElIcon: typeof import('element-plus/es/components/icon/index')['ElIcon']
    ElPopover: typeof import('element-plus/es/components/popover/index')['ElPopover']
    ElTooltip: typeof import('element-plus/es/components/tooltip/index')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
